<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.2.0-rc.1</Version>
    <AssemblyVersion>1.2.0.0</AssemblyVersion>
    <FileVersion>1.2.0.0</FileVersion>
    <InformationalVersion>1.2.0-rc.1</InformationalVersion>
  </PropertyGroup>

	<ItemGroup Condition="'$(Configuration)' == 'Debug'">
		<ProjectReference Include="..\Mercury.Abstractions\Mercury.Abstractions.csproj" />
		<ProjectReference Include="..\Mercury.Core\Mercury.Core.csproj" />
		<ProjectReference Include="..\Mercury.Extensions.EasySetup\Mercury.Extensions.EasySetup.csproj" />
		<ProjectReference Include="..\Mercury.Provider.AesCcm\Mercury.Provider.AesCcm.csproj" />
		<ProjectReference Include="..\Mercury.Provider.AesGcm\Mercury.Provider.AesGcm.csproj" />
		<ProjectReference Include="..\Mercury.Provider.ChaCha20\Mercury.Provider.ChaCha20.csproj" />
		<ProjectReference Include="..\Mercury.Transport.FileDrop\Mercury.Transport.FileDrop.csproj" />
		<ProjectReference Include="..\Mercury.Transport.InMemory\Mercury.Transport.InMemory.csproj" />
		<ProjectReference Include="..\Mercury.Transport.Tcp\Mercury.Transport.Tcp.csproj" />
	</ItemGroup>

	<ItemGroup Condition="'$(Configuration)' == 'Release'">
		<Reference Include="Mercury.Abstractions">
			<HintPath>..\Dlls\Release\Mercury.Abstractions.dll</HintPath>
			<Private>true</Private>
		</Reference>

		<Reference Include="Mercury.Core">
			<HintPath>..\Dlls\Release\Mercury.Core.dll</HintPath>
			<Private>true</Private>
		</Reference>

		<Reference Include="Mercury.Core">
			<HintPath>..\Dlls\Release\Mercury.Extensions.EasySetup.dll</HintPath>
			<Private>true</Private>
		</Reference>

		<Reference Include="Mercury.Core">
			<HintPath>..\Dlls\Release\Mercury.Provider.AesCcm.dll</HintPath>
			<Private>true</Private>
		</Reference>

		<Reference Include="Mercury.Core">
			<HintPath>..\Dlls\Release\Mercury.Provider.AesGcm.dll</HintPath>
			<Private>true</Private>
		</Reference>

		<Reference Include="Mercury.Core">
			<HintPath>..\Dlls\Release\Mercury.Provider.ChaCha20.dll</HintPath>
			<Private>true</Private>
		</Reference>

		<Reference Include="Mercury.Core">
			<HintPath>..\Dlls\Release\Mercury.Transport.FileDrop.dll</HintPath>
			<Private>true</Private>
		</Reference>

		<Reference Include="Mercury.Core">
			<HintPath>..\Dlls\Release\Mercury.Transport.InMemory.dll</HintPath>
			<Private>true</Private>
		</Reference>

		<Reference Include="Mercury.Core">
			<HintPath>..\Dlls\Release\Mercury.Transport.Tcp.dll</HintPath>
			<Private>true</Private>
		</Reference>
	</ItemGroup>

  <!--<ItemGroup>
    <ProjectReference Include="..\Mercury.Abstractions\Mercury.Abstractions.csproj" />
    <ProjectReference Include="..\Mercury.Core\Mercury.Core.csproj" />
    <ProjectReference Include="..\Mercury.Provider.AesGcm\Mercury.Provider.AesGcm.csproj" />
    <ProjectReference Include="..\Mercury.Provider.ChaCha20\Mercury.Provider.ChaCha20.csproj" />
    <ProjectReference Include="..\Mercury.Transport.InMemory\Mercury.Transport.InMemory.csproj" />
    <ProjectReference Include="..\Mercury.Transport.Tcp\Mercury.Transport.Tcp.csproj" />
  </ItemGroup>-->

</Project>
