<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<Reference Include="Mercury.Abstractions">
			<HintPath>..\Dlls\$(Configuration)\Mercury.Abstractions.dll</HintPath>
			<Private>true</Private>
		</Reference>
	</ItemGroup>

	<Target Name="CopyDllToSolution"
	        AfterTargets="Build"
	        Condition="'$(OS)' == 'Windows_NT' And '$(SolutionDir)' != ''">
		<Exec Command="if not exist &quot;$(SolutionDir)Dlls\$(Configuration)&quot; mkdir &quot;$(SolutionDir)Dlls\$(Configuration)&quot;&#xD;&#xA;copy /Y &quot;$(TargetPath)&quot; &quot;$(SolutionDir)Dlls\$(Configuration)\&quot;" />
	</Target>

</Project>
